<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Condor.Core\Condor.Core.csproj" />
    <ProjectReference Include="..\Condor.Infrastructure\Condor.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>condor</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
